import path from "path";
import fs from "fs";
import { mdToPdf } from "md-to-pdf";

export default async function PdfDownload() {
  // const { fileName } = await generatePdf();
  const  fileName  = ""
        

  const date = new Date().toLocaleDateString().replace(/\//g, "-");

  return (
    <a
      href={fileName}
      target="_blank"
      download={fileName.replace(/\.pdf/g, `-${date}.pdf`)}
    >
      Download
    </a>
  );
}

export const generatePdf = async () => {
  const aboutPath = "content/about.md";
  const globalStylesheet = path.resolve("styles/", "global.css");
  const publicFolder = path.resolve(".", "public");

  // Update if need highlight style, if not use global style raise error due wrong path.
  const highlight_style = path.resolve("styles/", "global");

  const fileName = `ricardo-arruda-resume-generated.pdf`;

  const fileExists = fs.existsSync(path.join(publicFolder, fileName));
  if (fileExists) {
    return {
      fileName,
    };
  }

  await mdToPdf(
    { path: aboutPath },
    {
      highlight_style,
      basedir: __dirname,
      dest: path.join(publicFolder, fileName),
      document_title: "Ricardo Arruda Resume",
      stylesheet: [globalStylesheet],
      css: `
         .markdown-body { font-size: 0.7rem; padding: 0.5rem 0.1rem; }
         .page-break { page-break-after: always; }
         .markdown-body pre > code { white-space: pre-wrap; }
         .markdown-body hr { padding: 0, margin: 0; }
      `,
      body_class: ["markdown-body"],
      page_media_type: "screen",
      pdf_options: {
        displayHeaderFooter: true,
        footerTemplate: `
            <style>
              * {
                  -webkit-print-color-adjust: exact;
                  background-color: #000000; 
               }
             </style>
            <div style="position: relative; bottom: -5px; padding: 0; margin:0; letter-spacing: 0.06em; text-align: center; width: 100%; font-size: 10px; font-family: trebuchet ms, Verdana, verdana ref, segoe ui, Candara, lucida grande, lucida sans unicode, lucida sans, Tahoma, sans-serif;">
                 <span style="color: IndianRed;" > pdf auto-generated by </span> <a href="https://arruda.dev/about" style="color: #83a8c0; text-decoration: none; border: none;">arruda.dev/about</a>
            </div>
        `,
        margin: { top: 0, right: 0, bottom: 30, left: 0 },
        pageRanges: "1-1",
        format: "a4",
        printBackground: true,
      },
      launch_options: {
        headless: true,
        args: ["--no-sandbox"],
      },
    },
  );

  return {
    fileName,
  };
};
